Triade/Controllers/ProdutosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Triade.Models;
using Triade.Repository.IRepository;
using Triade.ViewModels;

namespace Triade.Controllers
{
    [Authorize]
    public class ProdutosController : Controller
    {
        #region Construtor
        private readonly IProdutosRepository _produtosRepository;
        private readonly IRequisitadosRepository _requisitadosRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;

        public ProdutosController(IProdutosRepository produtosRepository, IRequisitadosRepository requisitadosRepository, IMapper mapper, UserManager<IdentityUser> userManager)
        {
            _produtosRepository = produtosRepository;
            _requisitadosRepository = requisitadosRepository;
            _mapper = mapper;
            _userManager = userManager;
        }
        #endregion

        #region Crud Create/Read/Update/Delete
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _produtosRepository.GetAll(x => x.Qtdproduto > 0).ConfigureAwait(true) });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(new Produtos());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Produtos produto)
        {
            produto.Created = DateTime.Now;

            if (ModelState.IsValid)
            {
                var adding = await _produtosRepository.Add(produto);

                if (adding == true)
                {
                    return Json(new { success = true, message = "Adicionado com Sucesso" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao adicionar. Verifique os campos!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Falha ao adicionar. Verifique os campos!" });
            }                       
        }
        
        [HttpGet]
        public IActionResult CreateProdutoComposto()
        {
            return View(new Produtos());
        }

        [HttpPost]
        public async Task<IActionResult> CreateProdutoComposto(Produtos produto)
        {
            produto.Created = DateTime.Now;

            if (ModelState.IsValid)
            {
                var adding = await _produtosRepository.Add(produto);

                if (adding == true)
                {
                    return Json(new { success = true, message = "Adicionado com Sucesso" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao adicionar. Verifique os campos!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Falha ao adicionar. Verifique os campos!" });
            }                       
        }
        
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var model = await _produtosRepository.Get(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Produtos produto)
        {
            if (ModelState.IsValid)
            {
                produto.Updated = DateTime.Now;
                var adding = await _produtosRepository.Update(produto);

                if (adding == true)
                {
                    return Json(new { success = true, message = "Atualizado com Sucesso" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao Atualizar. Verifique os campos!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Falha ao Atualizar. Verifique os campos!" });
            }                       
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var objFromDB = _produtosRepository.Remove(id);
            if (objFromDB == null || objFromDB.Result == false)
            {
                return Json(new { success = false, message = "Erro enquanto estava deletando" });
            }
            return Json(new { success = true, message = "Deletado com Sucesso" });
        }
        #endregion

        #region Retirar Produto
        [HttpGet]
        public async Task<IActionResult> RequisitarProduto(int id)
        {
            var model = _mapper.Map<ProdutosVM>(await _produtosRepository.Get(id));

            model.QtdRequisitadaOuRetirada = 0;

            return Json(new { model });
        }

        [HttpPost]
        public async Task<IActionResult> RequisitarProduto(ProdutosVM produtovm)
        {
            if (ModelState.IsValid)
            {
                produtovm.Updated = DateTime.Now;
                var produto = _mapper.Map<Produtos>(produtovm);

                produto.Qtdproduto -= produtovm.QtdRequisitadaOuRetirada;

                var updatingQtd = await _produtosRepository.Update(produto);

                if (updatingQtd == true)
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(true);
                    
                    var retirado = new Requisitados()
                    {
                        ProdutoId = produto.Id,
                        QtdRequisitada = produtovm.QtdRequisitadaOuRetirada,
                        UserId = user.Id,
                        DataRequisitada = DateTime.Now,
                        Created = DateTime.Now,
                    };

                    await _requisitadosRepository.Update(retirado);

                    return Json(new { success = true, message = "Quantidade atualizada com Sucesso" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao atualizar quantidade. Verifique os campos!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Falha ao atualizar quantidade. Verifique os campos!" });
            }                       
        }
        
        [HttpGet]
        public async Task<IActionResult> AdicionarQtdProduto(int id)
        {
            var model = _mapper.Map<ProdutosVM>(await _produtosRepository.Get(id));

            model.QtdRequisitadaOuRetirada = 0;

            return Json(new { model });
        }

        [HttpPost]
        public async Task<IActionResult> AdicionarQtdProduto(ProdutosVM produtovm)
        {
            if (ModelState.IsValid)
            {
                produtovm.Updated = DateTime.Now;
                var produto = _mapper.Map<Produtos>(produtovm);

                produto.Qtdproduto += produtovm.QtdRequisitadaOuRetirada;

                var updatingQtd = await _produtosRepository.Update(produto);

                if (updatingQtd == true)
                {
                    return Json(new { success = true, message = "Quantidade atualizada com Sucesso" });
                }
                else
                {
                    return Json(new { success = false, message = "Falha ao atualizar quantidade. Verifique os campos!" });
                }
            }
            else
            {
                return Json(new { success = false, message = "Falha ao atualizar quantidade. Verifique os campos!" });
            }                       
        }
        #endregion

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Triade/Controllers/RelatoriosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Triade.Models;
using Triade.Repository.IRepository;
using Triade.ViewModels;

namespace Triade.Controllers
{
    [Authorize]
    public class RelatoriosController : Controller
    {
        #region Construtor
        private readonly IProdutosRepository _produtosRepository;
        private readonly IRetiradosRepository _retiradosRepository;
        private readonly IRequisitadosRepository _requisitadosRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<IdentityUser> _userManager;

        public RelatoriosController(IProdutosRepository produtosRepository, IRetiradosRepository retiradosRepository, IRequisitadosRepository requisitadosRepository, IMapper mapper, UserManager<IdentityUser> userManager)
        {
            _produtosRepository = produtosRepository;
            _retiradosRepository = retiradosRepository;
            _requisitadosRepository = requisitadosRepository;
            _mapper = mapper;
            _userManager = userManager;
        }
        #endregion
                
        public IActionResult SaidasEstoque()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllSaidasEstoque()
        {
            var model = await _retiradosRepository.GetAll(includeProperties: "Produto").ConfigureAwait(true);

            var retiradosList = new List<RetiradosVM>();
            foreach(var retirado in model.Where(x=> x.Produto.ProdutoTipo == Produtos.ProductType.Simples))
            {
                var user = await _userManager.FindByIdAsync(retirado.UserId).ConfigureAwait(true);

                var retToAdd = new RetiradosVM()
                {
                    Produto = retirado.Produto,
                    DataRetirada = retirado.DataRetirada,
                    QtdRetirada = retirado.QtdRetirada,
                    Usuario = user
                };

                retiradosList.Add(retToAdd);
            }            

            return Json(new { data = retiradosList });
        }

        public IActionResult Requisicoes()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllRequisicoes()
        {
            return Json(new { data = await _requisitadosRepository.GetAll(includeProperties: "Produto").ConfigureAwait(true) });
        }

        [HttpGet]
        public async Task<IActionResult> VoltarRequisicao(int id)
        {
            var requisicao = await _requisitadosRepository.GetFirstOrDefault(x => x.Id == id);

            var produto = await _produtosRepository.Get(requisicao.ProdutoId);

            produto.Qtdproduto += requisicao.QtdRequisitada;

            await _produtosRepository.Update(produto);
            await _requisitadosRepository.Remove(id);

            return Json(new { success = true, message = "Requisição finalizada e quantidade voltada para Produtos!" });
        }

        #region Retirar Produto
        [HttpGet]
        public async Task<IActionResult> RetirarRequisicao(int id)
        {
            var model = _mapper.Map<Requisitados>(await _requisitadosRepository.GetFirstOrDefault(x=> x.Id == id, includeProperties: "Produto"));

            return Json(new { model });
        }

        [HttpPost]
        public async Task<IActionResult> RetirarRequisicao(RetiradosRequisicaoVM retiradoRequisicao)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(HttpContext.User).ConfigureAwait(true);

                var retirado = new Retirados()
                {
                    DataRetirada = DateTime.Now,
                    Created = DateTime.Now,
                    UserId = user.Id,
                    ProdutoId = retiradoRequisicao.ProdutoId,
                    QtdRetirada = retiradoRequisicao.QtdRetirada
                };

                await _retiradosRepository.Update(retirado);

                await _requisitadosRepository.Remove(retiradoRequisicao.RequisicaoId);

                return Json(new { success = true, message = "Requisição finalizada com Sucesso" });
            }
            else
            {
                return Json(new { success = false, message = "Falha ao finalizar requisição!" });
            }
        }
        #endregion


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Triade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tríade Soluções Inteligentes, Ltda.</title>    
    <link rel="icon" type="image/x-icon" href="~/favicon.jpg">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/datetime/1.1.1/css/dataTables.dateTime.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Tríade MultiClubes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Relatorios" asp-action="Requisicoes">Requisições</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Relatorios" asp-action="SaidasEstoque">Saídas de Estoque</a>
                        </li>                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Tríade Soluções Inteligentes, Ltda.
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/datetime/1.1.1/js/dataTables.dateTime.min.js"></script>
    <script src="https://kit.fontawesome.com/60317791f5.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>